version: "3.9"
services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  api:
    build:
      context: ./backend
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongo:27017/roomsync
      - PORT=4000
      - JWT_SECRET=${JWT_SECRET}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS:-*}
    ports:
      - "4000:4000"
    depends_on:
      - mongo
volumes:
  mongo_data: 