services:
- type: web
  name: roomsync-backend
  env: docker
  plan: starter
  autoDeploy: true
  healthCheckPath: /healthz
  dockerfilePath: backend/Dockerfile
  buildContext: ./backend
  envVars:
  - key: NODE_ENV
    value: production
  - key: PORT
    value: 4000
  - key: MONGO_URI
    sync: false
  - key: JWT_SECRET
    sync: false
  - key: ALLOWED_ORIGINS
    value: "*"
  - key: TRUST_PROXY
    value: "true"
  - key: ENFORCE_HTTPS
    value: "true"
  - key: RATE_LIMIT_WINDOW_MS
    value: "900000"
  - key: RATE_LIMIT_MAX
    value: "300"
  - key: CLOUDINARY_URL
    sync: false
  - key: OPENAI_API_KEY
    sync: false 